### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by oscarvalenzuelab** [jcftang/logentriesrus#3]
Hi,

I like your project, this is a transitive dependency of another project I'm using, but I'm wondering what is the license? Should be MIT like your other projects?

Thanks!

**Comment by jcftang** [comment]
Yep MIT license is fine, someone else reached out asking about this as well, there may be a PR soon for adding a license.

**Comment by jcftang** [comment]
see https://github.com/jcftang/logentriesrus/pull/4, license now added
